#!/bin/bash

NAME="$1"
if [ -z "$NAME" ]; then
  echo "usage: create-cluster <name>"
  exit 1
fi

CLUSTER_DIR="${HOME}/clusters/${NAME}"
if [ -d "${CLUSTER_DIR}" ]; then
  echo "WARNING: cluster ${NAME} already exists at ${CLUSTER_DIR}"
else
  mkdir -p ${CLUSTER_DIR}
fi
# Generate a default SSH key if one doesn't exist
SSH_KEY="${HOME}/.ssh/id_rsa"
if [ ! -f $SSH_KEY ]; then
  ssh-keygen -t rsa -N "" -f $SSH_KEY
fi
export BASE_DOMAIN=openshift.testing
export CLUSTER_NAME="${NAME}"
export PUB_SSH_KEY="${SSH_KEY}.pub"
export BUILD=$(curl -s https://releases-rhcos.svc.ci.openshift.org/storage/releases/maipo/builds.json | jq -r '.builds[0]')

cat > "${CLUSTER_DIR}/install-config.yaml" << EOF
apiVersion: v1beta3
baseDomain: "${BASE_DOMAIN}"
compute:
- name: worker
  replicas: 1
controlPlane:
  name: master
  replicas: 1
metadata:
  name: "${CLUSTER_NAME}"
networking:
  machineCIDR: 192.168.126.0/24
platform:
  libvirt:
    defaultMachinePlatform:
      image: "https://releases-rhcos.svc.ci.openshift.org/storage/releases/maipo/${BUILD}/redhat-coreos-maipo-${BUILD}-qemu.qcow2.gz"

pullSecret: '$(curl http://metadata.google.internal/computeMetadata/v1/instance/attributes/openshift-pull-secret -H "Metadata-Flavor: Google")'
sshKey: |
  $(cat "${PUB_SSH_KEY}")
EOF

openshift-install create cluster --log-level=debug --dir="$CLUSTER_DIR" 2>&1 | tee /tmp/installer.log
