#!/bin/bash

NAME="$1"
if [ -z "$NAME" ]; then
  echo "usage: create-single-node-cluster <name>"
  exit 1
fi

# https://origin-release.apps.ci.l2s4.p1.openshiftapps.com/#4.5.0-0.okd
if [[ -z "$OKD_RELEASE_IMAGE" ]]; then
    export OKD_RELEASE_IMAGE=quay.io/openshift/okd:4.5.0-0.okd-2020-07-14-153706-ga
fi

# extract libvirt installer from okd image
oc adm release extract --command openshift-baremetal-install "${OKD_RELEASE_IMAGE}" 
sudo mv openshift-baremetal-install /usr/local/bin/openshift-install 

CLUSTER_DIR="${HOME}/clusters/${NAME}"
if [ -d "${CLUSTER_DIR}" ]; then
  echo "WARNING: cluster ${NAME} already exists at ${CLUSTER_DIR}"
else
  mkdir -p ${CLUSTER_DIR}
fi
# Generate a default SSH key if one doesn't exist
SSH_KEY="${HOME}/.ssh/id_rsa"
if [ ! -f $SSH_KEY ]; then
  ssh-keygen -t rsa -N "" -f $SSH_KEY
fi
export BASE_DOMAIN=openshift.testing
export CLUSTER_NAME="${NAME}"
export PUB_SSH_KEY="${SSH_KEY}.pub"

cat > "${CLUSTER_DIR}/install-config.yaml" << EOF
apiVersion: v1
baseDomain: "${BASE_DOMAIN}"
compute:
- hyperthreading: Enabled
  architecture: amd64
  name: worker
  platform: {}
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  architecture: amd64
  name: master
  platform: {}
  replicas: 1
metadata:
  creationTimestamp: null
  name: "${CLUSTER_NAME}"
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.126.0/24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  libvirt:
    network:
      if: tt0
publish: External
pullSecret: '{"auths":{"not-required":{"auth":"notrequired","email":"public@open.com"}}}'
sshKey: |
  $(cat "${PUB_SSH_KEY}")
EOF

# Create manifests and modify route domain
openshift-install --dir="$CLUSTER_DIR" create manifests
# Workaround for https://github.com/openshift/installer/issues/1007
# Add custom domain to cluster-ingress
yq write --inplace $CLUSTER_DIR/manifests/cluster-ingress-02-config.yml spec[domain] apps.$BASE_DOMAIN

# Add master memory to 12 GB
# This is only valid for openshift 4.3 onwards
yq write --inplace ${CLUSTER_DIR}/openshift/99_openshift-cluster-api_master-machines-0.yaml spec.providerSpec.value[domainMemory] 14336

openshift-install create cluster --log-level=debug --dir="$CLUSTER_DIR" || true
openshift-install wait-for install-complete --log-level=debug --dir="$CLUSTER_DIR"
