#!/bin/bash
set -e
set -u
set -o pipefail

echo "Building installer"

REPO_OWNER="${1:-openshift}"
BRANCH="${2:-master}"
GOPATH=$(mktemp -d)
export GOPATH

git clone https://github.com/"${REPO_OWNER}"/installer.git $GOPATH/src/github.com/openshift/installer
cd $GOPATH/src/github.com/openshift/installer
git checkout "${BRANCH}"

TAGS=libvirt hack/build.sh

sudo mv bin/openshift-install /usr/local/bin

sudo rm -rf $GOPATH
