#!/bin/bash

dest="${1:-/var/lib}"

build=$(curl -s https://releases-rhcos.svc.ci.openshift.org/storage/releases/maipo/builds.json | jq -r '.builds[0]')
image=$(curl -s https://releases-rhcos.svc.ci.openshift.org/storage/releases/maipo/$build/meta.json | jq -r '.images["qemu"].path')
url="https://releases-rhcos.svc.ci.openshift.org/storage/releases/maipo/$build/$image"
output="$dest/redhat-coreos-maipo-latest-qemu.qcow2"

echo "Downloading rhcos $build to $output"
sudo curl --compressed -L -o $output $url
